export const paths = {
  home: '/',
  fleet: '/fleet',
  fleetSearch: (from: string, to: string) => `/fleet?from=${from}&to=${to}`,
  checkout: (carId: string) => `/checkout/${carId}`,
  verifyId: '/booking/verify/id',
  verifyInsurance: '/booking/verify/insurance',
  booking: (id: string) => `/booking/${id}`,
  paymentPending: (id: string) => `/booking/${id}/payment-pending`,
  modify: (id: string) => `/booking/${id}/modify`,
  swap: (id: string) => `/booking/${id}/swap`,
  cancel: (id: string) => `/booking/${id}/cancel`,
  agreement: (id: string | number) => `/rental-agreement/${id}`,
  terms: '/terms',
  privacy: '/privacy',
  manage: '/manage',
  bookings: '/bookings',
  signIn: '/sign-in',
  register: '/register',
} as const;
